Lekcja 5, zadanie 1 Barman, rozwiązanie
typowy1/bootcamp-javastart-zadania pull request #15
Opened 2020-10-15 10:52 UTC by typowy1

Rozwiązanie

2020-10-15 17:41 UTC, paweljavastart requested changes

2020-10-15 17:41 UTC, paweljavastart commented on src/lekcja5_zadanie1_barman/Barman.java
> +        return null;
zwracanie nulla w tym przypadku jest  niepotrzebne a dodatkowo ryzykowne (ryzyko `NullPointerException`).  Wystarczy obsluzyc wszystkie przypadki w wyrazeniu `if` i zawsze zwracać `String` .

2020-10-16 06:57 UTC, typowy1 commented on src/lekcja5_zadanie1_barman/Barman.java
> +        return null;
Poprawione

2020-10-16 14:56 UTC, paweljavastart approved these changes

2020-10-16 15:03 UTC, merged