Lekcja 5, zadanie 2 Pokój z klimatyzacją, rozwiązanie uwzględniające dodatkowe zadanie
typowy1/bootcamp-javastart-zadania pull request #16
Opened 2020-10-15 16:33 UTC by typowy1

Lekcja 5, zadanie 2 Pokój z klimatyzacją, rozwiązanie uwzględniające informację o kubaturze pomieszczenia i wydajności klimatyzatora.

2020-10-15 17:48 UTC, paweljavastart requested changes

2020-10-15 17:48 UTC, paweljavastart commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +        if (isAirConditioning() && temperature > 20) {
uzyj pola `airConditioning` zamiast metody `isAirConditioning()`

2020-10-15 17:48 UTC, paweljavastart commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +    private boolean loweringTemperature() {
nazwij metode `lowerTemperature`

2020-10-15 17:48 UTC, paweljavastart commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +    public String loweringTemperatureAndCheck() {
nazwij metode `lowerTemperatureAndCheck`

2020-10-16 06:28 UTC, typowy1 commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +    public String loweringTemperatureAndCheck() {
Poprawione

2020-10-16 06:28 UTC, typowy1 commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +    private boolean loweringTemperature() {
Poprawione

2020-10-16 06:28 UTC, typowy1 commented on src/lekcja5_zadanie2_pokoj_z_klimatyzacja/Room.java
> +        if (isAirConditioning() && temperature > 20) {
Poprawione

2020-10-16 14:51 UTC, paweljavastart approved these changes

2020-10-16 15:03 UTC, merged