Lekcja8 zadanie2 bilety z typami i znizkami
typowy1/bootcamp-javastart-zadania pull request #26
Opened 2020-10-27 17:25 UTC by typowy1

Rozwiązanie

2020-10-27 18:43 UTC, paweljavastart requested changes

2020-10-27 18:43 UTC, paweljavastart commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +                    return tickets[i].getGiftPrice();
cena ma być  taka jak biletu standard, powiększona o dodatkowe 5% ceny podstawowej z uwzglednieniem znizki jesli jest. A tutaj obliczasz albo podstawowa cene ze znizka albo doliczsz dodatkowe 5%

2020-10-27 18:43 UTC, paweljavastart commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/BuyingTickets.java
> +        TicketUtils.getFinalPrice(tickets);
nie uzywasz zmiennej ktora jest zwracana przez ta metody.

2020-10-27 18:43 UTC, paweljavastart commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +        for (int i = 0; i < tickets.length; i++) {
nie rozumiem po co jest ta pętla.

2020-10-27 18:43 UTC, paweljavastart commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +    public static Double getFinalPrice(Ticket[] tickets) {
ta metoda powinna przyjąc `Ticket ticket` zamiast tablicy

2020-10-27 18:43 UTC, paweljavastart commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +            }
zamiast `if-else` lepiej zrobic tak:
```
   System.out.println("Cena przy zakupie jako " + tickets[i].getType()
                        + ", cena: " + getFinalPrice(tickets[i]));
```

2020-10-27 21:03 UTC, typowy1 commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +                    return tickets[i].getGiftPrice();
Poprawione

2020-10-27 21:03 UTC, typowy1 commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/BuyingTickets.java
> +        TicketUtils.getFinalPrice(tickets);
Poprawione

2020-10-27 21:04 UTC, typowy1 commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +        for (int i = 0; i < tickets.length; i++) {
Poprawione

2020-10-27 21:04 UTC, typowy1 commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +    public static Double getFinalPrice(Ticket[] tickets) {
Poprawione

2020-10-27 21:04 UTC, typowy1 commented on src/lekcja8_zadanie2_bilety_z_typami_i_znizkami/TicketUtils.java
> +            }
Poprawione

2020-10-28 06:48 UTC, paweljavastart approved these changes

2020-10-29 07:21 UTC, merged